config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :users, only: %i[new create]
  resources :accounts, only: %i[edit update destroy]

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"

  resources :llm_models, only: %i[index] do
    resources :capabilities, only: %i[index]
  end

  resources :chats, only: %i[new index show destroy] do
    resources :prompts, only: %i[edit update], controller: "chats/prompts"
    resources :messages, only: %i[new show edit create update] do
      resource :retry, only: [ :create ], controller: "messages/retry"
    end
    resource :cancel, only: [ :create ], controller: "chats/cancel"
  end

  if Rails.env.development?
    mount Lookbook::Engine, at: "/lookbook"
  end
  # Add a protected route that requires authentication
  mount MissionControl::Jobs::Engine, at: "/jobs"
end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id            :integer          not null, primary key
#  body          :string
#  is_system     :boolean          default(FALSE)
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  chat_id       :integer          not null
#  generation_id :integer
#
# Indexes
#
#  index_messages_on_chat_id        (chat_id)
#  index_messages_on_generation_id  (generation_id)
#
# Foreign Keys
#
#  chat_id        (chat_id => chats.id)
#  generation_id  (generation_id => generations.id)
#
class Message < ApplicationRecord
  belongs_to :chat
  has_many :citations, dependent: :destroy
  has_many :reasoning_chunks, dependent: :destroy
  belongs_to :generation, optional: true

  validates :chat, presence: true

  scope :ordered, -> { order(created_at: :asc) }
  scope :after_message, ->(message) { where("created_at > ?", message.created_at).order(created_at: :asc) }

  broadcasts_to ->(message) { [ message.chat, :messages ] }
end

app/controllers/messages/retry_controller.rb
class Messages::RetryController < ApplicationController
  def create
    message = Current.user.chats.find(params[:chat_id]).messages.find(params[:message_id])
    if message.chat.generating
      head :ok
      return
    end
    messages = message.chat.messages.after_message(message)

    generation = message.generation
    puts "generation: #{generation.inspect}"
    Message.transaction do
      message.chat.update!(generating: true)
      generation.update!(completed: false, canceled: false, content: "")
      if message.is_system
        message.destroy!
      end
      messages.destroy_all
    end
    puts "\n\n\n\n\n\n\n\n\nabout to generate retry"
    puts "generation: #{generation.inspect}"
    puts "\n\n\n\n\n\n\n\n\n"
    OpenrouterChatCompletionJob.perform_later(generation)

    head :ok
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :set_chat, only: %i[edit show create update]
    before_action :set_message, only: %i[edit show update]

    def show; end

    def edit; end

    def update
      if @message.update(message_params)
        render :show
      else
        render :edit
      end
    end

    def create
      @message = @chat.messages.new(message_params)
      if @message.save
        @chat.update!(generating: true)
        generation = @chat.generations.create!(
          llm_model: @chat.prompt.llm_model,
          content: "",
          search_enabled: @chat.prompt.searching && @chat.prompt.llm_model.can_search,
          reasoning_effort: @chat.prompt.reasoning && @chat.prompt.llm_model.can_reason ? "medium" : "none"
        )
        puts "CREATED GENERATION: #{generation.inspect}"
        @message.update!(generation: generation)
        OpenrouterChatCompletionJob.perform_later(generation)
        @message = @chat.messages.new
      end
      respond_to do |format|
        format.turbo_stream
      end
    end

    private

    def set_chat
        @chat = Current.user.chats.find(params[:chat_id])
    end

    def set_message
      @message = @chat.messages.find(params[:id])
    end

    def message_params
        params.require(:message).permit(:body)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_with(model: [@chat, message], id: dom_id(message), class: "flex flex-row items-center justify-between gap-4", data: { controller: "form-disable prompt" }) do |form| %>
  <%= form.text_area :body,
  {
                autocomplete: "off",
                placeholder: @chat.user.account.has_api_key? ? "Prompt..." : "Add your API key to chat",
                required: true,
                rows: 1,
                data: { form_disable_target: "element", action: "keydown->prompt#keydown input->prompt#resize" },
                class: "
                  flex-1 max-h-32 rounded-md resize-none border border-border bg-chat-entry p-2 text-base transition-all duration-200 text-text-primary placeholder-text-secondary focus:border-primary focus:outline-none focus:ring-0 overflow-y-auto
                  transition-colors duration-150 hover:bg-sidebar hover:border-primary
                "}.merge(disabled: !@chat.user.account.has_api_key?)
                %>
  <div id="send-button">
    <%= render "messages/send_button", chat: @chat %>
  </div>
<% end %>

app/views/messages/_loading_indicator.html.erb
<div id="loading-status" class="flex items-center gap-2 p-4 text-text-secondary">
    <div class="animate-spin">
        <%= heroicon "arrow-path", options: { class: "h-5 w-5" } %>
    </div>
    <span>Generating response...</span>
</div>

app/views/messages/_message.html.erb
<%# locals: (message:) %>
<% if message.is_system %>
  <%= render "messages/message_system", message: %>
<% else %>
  <%= render "messages/message_user", message: %>
<% end %>

app/views/messages/_message_bubble.html.erb
<div class="px-4 py-3 bg-chat-message rounded-lg border border-border")>
  <%= message.value %>
</div>

app/views/messages/_message_system.html.erb
<%# locals: (message:) %>
<%= turbo_frame_tag dom_id(message), class: "self-start", id: dom_id(message) do %>
  <%= render ChatBubbleComponent.new(is_system: true) do |bubble| %>
    <%= bubble.with_body do %>
      <% if message.reasoning_chunks.any? %>
        <details <%= "open" if message.chat.generating && message.body.blank? %>>
          <summary class="text-sm font-light text-gray-400">Reasoning</summary>
          <div class="prose prose-invert max-w-none">
            <%= markdown(message.reasoning_chunks.map(&:body).join("\n")) %>
          </div>
        </details>
        <hr class="my-8 border-gray-700">
      <% end %>
      <div class="prose prose-invert max-w-none">
        <%= markdown(message.body) %>
      </div>
    <% end %>
    <%= bubble.with_info do %>
      <div class="flex flex-col gap-2">
        <span class="font-thin text-xs"><%= message.generation.llm_model.model %></span>
        <% unless message.citations.empty? %>
          <h6 class="text-xs font-light text-gray-400">Citations</h6>
          <div class="flex flex-row gap-4">
            <% message.citations.each do |citation| %>
              <%= link_to citation.title, citation.url, class: "font-light text-xs text-blue-500 bg-blue-500/10 px-2 py-1 rounded-full border border-blue-500/20 hover:bg-blue-500/20" %>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>
    <%= bubble.with_action_button(href: chat_message_retry_path(message.chat, message), icon: "arrow-path") %>
  <% end %>
<% end %>

app/views/messages/_message_user.html.erb
<%# locals: (message:) %>
<%= turbo_frame_tag dom_id(message), class: "self-end", id: dom_id(message) do %>
  <%= render ChatBubbleComponent.new do |bubble| %>
    <%= bubble.with_body { markdown(message.body) } %>
    <%= bubble.with_action_button(href: chat_message_retry_path(message.chat, message), icon: "arrow-path") %>
    <%= bubble.with_action_link(href: edit_chat_message_path(message.chat, message), icon: "pencil-square", data: { turbo_frame: dom_id(message), }) %>
  <% end %>
<% end %>

app/views/messages/_send_button.html.erb
<% if chat.generating %>
  <%= link_to chat_cancel_path(chat), 
          data: { turbo_method: :post },
          class: "inline-flex items-center justify-center rounded-md p-2 text-text-primary hover:bg-chat-area transition-colors duration-200" do %>
    <%= heroicon "stop", options: { class: "h-5 w-5" } %>
  <% end %>
<% else %>
  <%= render ButtonComponent.new(
        icon: "paper-airplane", 
        type: :submit, 
        variant: :primary,
        disabled: !chat.user.account.has_api_key?,
        data: { 
          form_disable_target: "element",
          action: "form-disable#disable"
        }
      ) %>
<% end %>

app/views/messages/create.turbo_stream.erb
<%= turbo_stream.replace dom_id(@message), partial: "messages/form", locals: { message: @message } %>

app/views/messages/edit.html.erb
<%= turbo_frame_tag dom_id(@message), class: "self-end", id: dom_id(@message) do %>
  <%= form_for([ @message.chat, @message ]) do |form| %>
    <%= render ChatBubbleComponent.new do |bubble| %>
      <%= bubble.with_body do %>
        <%= form.text_area :body %>
      <% end %>
      <%= bubble.with_action_link(href: chat_message_path(@message.chat, @message), icon: "x-mark", color: "text-green-500", data: { turbo_frame: dom_id(@message), }) %>
      <%= bubble.with_action_button(type: :submit, icon: "check", color: "text-green-500", data: { turbo_frame: dom_id(@message) }) %>
    <% end %>
  <% end %>
<% end %>

app/views/messages/show.html.erb
<%= render @message %>