config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :users, only: %i[new create]
  resources :accounts, only: %i[edit update destroy]

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"

  resources :llm_models, only: %i[index] do
    resources :capabilities, only: %i[index]
  end

  resources :chats, only: %i[new index show destroy] do
    resources :prompts, only: %i[edit update], controller: "chats/prompts"
    resources :messages, only: %i[new show edit create update] do
      resource :retry, only: [ :create ], controller: "messages/retry"
    end
    resource :cancel, only: [ :create ], controller: "chats/cancel"
  end

  if Rails.env.development?
    mount Lookbook::Engine, at: "/lookbook"
  end
  # Add a protected route that requires authentication
  mount MissionControl::Jobs::Engine, at: "/jobs"
end

app/models/chat.rb
# == Schema Information
#
# Table name: chats
#
#  id         :integer          not null, primary key
#  generating :boolean          default(FALSE)
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer          not null
#
# Indexes
#
#  index_chats_on_user_id  (user_id)
#
# Foreign Keys
#
#  user_id  (user_id => users.id)
#

class Chat < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
  has_many :generations, dependent: :destroy
  has_one :prompt, dependent: :destroy

  scope :ordered, -> { order(created_at: :desc) }

  validates :user, presence: true
  validates :title, presence: true

  broadcasts_to ->(chat) { [ chat.user, :chats ] }

  after_save_commit do
    broadcast_update_to(
      [ self, :send_button ],
      target: "send-button",
      partial: "messages/send_button",
      locals: { chat: self }
    )

    if generating
      broadcast_replace_to [ self, :loading_status ], target: "loading-status", partial: "messages/loading_indicator"
    else
      broadcast_update_to [ self, :loading_status ], target: "loading-status", html: ""
    end
  end
end

app/models/prompt.rb
# == Schema Information
#
# Table name: prompts
#
#  id           :integer          not null, primary key
#  body         :string
#  reasoning    :boolean
#  searching    :boolean
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  chat_id      :integer          not null
#  llm_model_id :integer          not null
#
# Indexes
#
#  index_prompts_on_chat_id       (chat_id)
#  index_prompts_on_llm_model_id  (llm_model_id)
#
# Foreign Keys
#
#  chat_id       (chat_id => chats.id)
#  llm_model_id  (llm_model_id => llm_models.id)
#
class Prompt < ApplicationRecord
  belongs_to :chat
  belongs_to :llm_model
end

app/controllers/chats/cancel_controller.rb
module Chats
  class CancelController < ApplicationController
    def create
      puts "\n\nCANCEL\n\n"
      chat = Current.user.chats.find(params[:chat_id])

      generation = chat.generations.where(canceled: false, completed: false).first

      puts "cancelling generation: #{generation.inspect}"

      raise "No generations to cancel!" unless generation

      Chat.transaction do
        generation.update!(canceled: true)
        chat.update!(generating: false)
      end

      head :ok
    end
  end
end

app/controllers/chats/prompts_controller.rb
class Chats::PromptsController < ApplicationController
    before_action :set_prompt

    def edit
    end

    def update
        puts "update-----", prompt_params
        @prompt.update(prompt_params)
        respond_to do |format|
            format.turbo_stream
        end
    end

    private

    def prompt_params
        raw = params.require(:prompt).permit(:body, :llm_model_id, :search_enabled, :reasoning_enabled).to_h
        raw[:searching] = raw.delete(:search_enabled)
        raw[:reasoning] = raw.delete(:reasoning_enabled)
        raw
    end

    def set_prompt
        @prompt ||= Current.user.chats.find(params[:chat_id]).prompt
    end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def index
    @chats = Current.user.chats.ordered
  end

  def new
    chat = nil
    Chat.transaction do
      chat = Current.user.chats.create!(title: "Untitled Chat #{Current.user.chats.count+1}")
      chat.prompt = Prompt.create!(chat: chat, llm_model: LlmModel.first)
    end
    redirect_to chat_path(chat)
  end

  def show
    @chat = Current.user.chats.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_url
  end

  def destroy
    @chat = Current.user.chats.find(params[:id])
    @chat.destroy
    redirect_to root_url 
  end
end

app/helpers/chats/prompts_helper.rb
module Chats::PromptsHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chats/prompts/_form.html.erb
<%# locals: (prompt:) %>
<%= form_with(model: [prompt.chat, prompt], id: dom_id(prompt), class: "h-2 flex-1 py-2 flex flex-row items-center gap-2 justify-start transition-all duration-100", data: { controller: "form-disable prompt", prompt_target: "form" }) do |form| %>
  <%= form.submit "Save", formaction: chat_prompt_path(prompt.chat), class: "hidden" %>
  <%= form.select :llm_model_id,
                    options_from_collection_for_select(LlmModel.all, :id, :name, prompt.llm_model.id),
                    {},
                    {
                      class: "bg-chat-entry rounded-md text-text-primary text-sm border-border border focus:ring-0 focus:outline-none appearance-none pr-8 py-2 pl-2 cursor-pointer transition-colors duration-150 hover:bg-sidebar hover:border-primary",
                      autocomplete: "off",
                      data: { action: "prompt#submit" }
                    } %>
  <div class="flex items-center gap-2">
    <% if prompt.llm_model.can_search %>
      <%= render ToggleComponent.new(form: form, attribute: :search_enabled, icon: "globe-alt", label: "Search", initial_checked: prompt.searching) %>
    <% end %>
    <% if prompt.llm_model.can_reason %>
      <%= render ToggleComponent.new(form: form, attribute: :reasoning_enabled, icon: "sparkles", label: "Think", initial_checked: prompt.reasoning) %>
    <% end %>
  </div>
<% end %>

app/views/chats/prompts/edit.html.erb
<%= render "chats/prompts/form", prompt: @prompt %>

app/views/chats/prompts/update.turbo_stream.erb
<%= turbo_stream.replace dom_id(@prompt) do %>
  <%= render partial: "chats/prompts/form", locals: { prompt: @prompt } %>
<% end %>